var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_PNA_Demographics_for_Dashboard_1 = new ol.format.GeoJSON();
var features_PNA_Demographics_for_Dashboard_1 = format_PNA_Demographics_for_Dashboard_1.readFeatures(json_PNA_Demographics_for_Dashboard_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_PNA_Demographics_for_Dashboard_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_PNA_Demographics_for_Dashboard_1.addFeatures(features_PNA_Demographics_for_Dashboard_1);
var lyr_PNA_Demographics_for_Dashboard_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_PNA_Demographics_for_Dashboard_1, 
                style: style_PNA_Demographics_for_Dashboard_1,
                popuplayertitle: "PNA_Demographics_for_Dashboard",
                interactive: true,
    title: 'PNA_Demographics_for_Dashboard<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_0.png" /> 0 - 2<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_1.png" /> 2 - 6.1<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_2.png" /> 6.1 - 12.5<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_3.png" /> 12.5 - 32.2<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_4.png" /> 32.2 - 69.9<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_5.png" /> 69.9 - 97<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_6.png" /> 97 - 263.8<br />\
    <img src="styles/legend/PNA_Demographics_for_Dashboard_1_7.png" /> 263.8 - 1295.7<br />'
        });

lyr_OpenStreetMap_0.setVisible(true);lyr_PNA_Demographics_for_Dashboard_1.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_PNA_Demographics_for_Dashboard_1];
lyr_PNA_Demographics_for_Dashboard_1.set('fieldAliases', {'STUD_AR_ID': 'STUD_AR_ID', 'STUD_AR_NM': 'STUD_AR_NM', 'STUD_AR_LB': 'STUD_AR_LB', 'TOOLKIT_ID': 'TOOLKIT_ID', 'Acres': 'Acres', 'AC_PER_1K': 'AC_PER_1K', 'RepPrkAc': 'RepPrkAc', 'NEED_DESCP': 'NEED_DESCP', 'PCT_Walk': 'PCT_Walk', 'aggregatio': 'aggregatio', 'HasData': 'HasData', 'ORIGINAL_O': 'ORIGINAL_O', 'sourceCoun': 'sourceCoun', 'population': 'population', 'householdt': 'householdt', 'householdi': 'householdi', 'educationa': 'educationa', 'educatio_1': 'educatio_1', 'educatio_2': 'educatio_2', 'educatio_3': 'educatio_3', 'educatio_4': 'educatio_4', 'educatio_5': 'educatio_5', 'educatio_6': 'educatio_6', 'educatio_7': 'educatio_7', 'educatio_8': 'educatio_8', 'sports_mp3': 'sports_mp3', 'sports_m_1': 'sports_m_1', 'sports_m_2': 'sports_m_2', 'sports_m_3': 'sports_m_3', 'sports_m_4': 'sports_m_4', 'sports_m_5': 'sports_m_5', 'sports_m_6': 'sports_m_6', 'sports_m_7': 'sports_m_7', 'sports_m_8': 'sports_m_8', 'sports_m_9': 'sports_m_9', 'sports__10': 'sports__10', 'sports__11': 'sports__11', 'sports__12': 'sports__12', 'sports__13': 'sports__13', 'F5yearincr': 'F5yearincr', 'F5yearin_1': 'F5yearin_1', 'F5yearin_2': 'F5yearin_2', 'F5yearin_3': 'F5yearin_3', 'F5yearin_4': 'F5yearin_4', 'F5yearin_5': 'F5yearin_5', 'F5yearin_6': 'F5yearin_6', 'F5yearin_7': 'F5yearin_7', 'F5yearin_8': 'F5yearin_8', 'F5yearin_9': 'F5yearin_9', 'F5yeari_10': 'F5yeari_10', 'F5yeari_11': 'F5yeari_11', 'F5yeari_12': 'F5yeari_12', 'F5yeari_13': 'F5yeari_13', 'F5yeari_14': 'F5yeari_14', 'F5yeari_15': 'F5yeari_15', 'F5yeari_16': 'F5yeari_16', 'F5yeari_17': 'F5yeari_17', 'F5yeari_18': 'F5yeari_18', 'F1yearincr': 'F1yearincr', 'F1yearin_1': 'F1yearin_1', 'MEAN_Asthm': 'MEAN_Asthm', 'MEAN_Low_B': 'MEAN_Low_B', 'MEAN_Cardi': 'MEAN_Cardi', 'aggregat_1': 'aggregat_1', 'HasData_1': 'HasData_1', 'ORIGINAL_1': 'ORIGINAL_1', 'sourceCo_1': 'sourceCo_1', 'raceandhis': 'raceandhis', 'raceandh_1': 'raceandh_1', 'raceandh_2': 'raceandh_2', 'raceandh_3': 'raceandh_3', 'raceandh_4': 'raceandh_4', 'raceandh_5': 'raceandh_5', 'raceandh_6': 'raceandh_6', 'raceandh_7': 'raceandh_7', 'raceandh_8': 'raceandh_8', 'Age0_17Pct': 'Age0_17Pct', 'Age18_34Pc': 'Age18_34Pc', 'Age35_54Pc': 'Age35_54Pc', 'Age55_69Pc': 'Age55_69Pc', 'Age70upPct': 'Age70upPct', 'HispanicPc': 'HispanicPc', 'WhitePct': 'WhitePct', 'Black_Pct': 'Black_Pct', 'Asian_Pct': 'Asian_Pct', 'Am_Indian': 'Am_Indian', 'Pac_Island': 'Pac_Island', 'Other_Race': 'Other_Race', 'Multi_Race': 'Multi_Race', 'No_HS': 'No_HS', 'HS_Grad': 'HS_Grad', 'Some_Colle': 'Some_Colle', 'College': 'College', 'unemprt_cy': 'unemprt_cy', });
lyr_PNA_Demographics_for_Dashboard_1.set('fieldImages', {'STUD_AR_ID': 'TextEdit', 'STUD_AR_NM': 'TextEdit', 'STUD_AR_LB': 'TextEdit', 'TOOLKIT_ID': 'Range', 'Acres': 'TextEdit', 'AC_PER_1K': 'TextEdit', 'RepPrkAc': 'TextEdit', 'NEED_DESCP': 'TextEdit', 'PCT_Walk': 'TextEdit', 'aggregatio': 'TextEdit', 'HasData': 'TextEdit', 'ORIGINAL_O': 'TextEdit', 'sourceCoun': 'TextEdit', 'population': 'TextEdit', 'householdt': 'TextEdit', 'householdi': 'TextEdit', 'educationa': 'TextEdit', 'educatio_1': 'TextEdit', 'educatio_2': 'TextEdit', 'educatio_3': 'TextEdit', 'educatio_4': 'TextEdit', 'educatio_5': 'TextEdit', 'educatio_6': 'TextEdit', 'educatio_7': 'TextEdit', 'educatio_8': 'TextEdit', 'sports_mp3': 'TextEdit', 'sports_m_1': 'TextEdit', 'sports_m_2': 'TextEdit', 'sports_m_3': 'TextEdit', 'sports_m_4': 'TextEdit', 'sports_m_5': 'TextEdit', 'sports_m_6': 'TextEdit', 'sports_m_7': 'TextEdit', 'sports_m_8': 'TextEdit', 'sports_m_9': 'TextEdit', 'sports__10': 'TextEdit', 'sports__11': 'TextEdit', 'sports__12': 'TextEdit', 'sports__13': 'TextEdit', 'F5yearincr': 'TextEdit', 'F5yearin_1': 'TextEdit', 'F5yearin_2': 'TextEdit', 'F5yearin_3': 'TextEdit', 'F5yearin_4': 'TextEdit', 'F5yearin_5': 'TextEdit', 'F5yearin_6': 'TextEdit', 'F5yearin_7': 'TextEdit', 'F5yearin_8': 'TextEdit', 'F5yearin_9': 'TextEdit', 'F5yeari_10': 'TextEdit', 'F5yeari_11': 'TextEdit', 'F5yeari_12': 'TextEdit', 'F5yeari_13': 'TextEdit', 'F5yeari_14': 'TextEdit', 'F5yeari_15': 'TextEdit', 'F5yeari_16': 'TextEdit', 'F5yeari_17': 'TextEdit', 'F5yeari_18': 'TextEdit', 'F1yearincr': 'TextEdit', 'F1yearin_1': 'TextEdit', 'MEAN_Asthm': 'TextEdit', 'MEAN_Low_B': 'TextEdit', 'MEAN_Cardi': 'TextEdit', 'aggregat_1': 'TextEdit', 'HasData_1': 'TextEdit', 'ORIGINAL_1': 'TextEdit', 'sourceCo_1': 'TextEdit', 'raceandhis': 'TextEdit', 'raceandh_1': 'TextEdit', 'raceandh_2': 'TextEdit', 'raceandh_3': 'TextEdit', 'raceandh_4': 'TextEdit', 'raceandh_5': 'TextEdit', 'raceandh_6': 'TextEdit', 'raceandh_7': 'TextEdit', 'raceandh_8': 'TextEdit', 'Age0_17Pct': 'TextEdit', 'Age18_34Pc': 'TextEdit', 'Age35_54Pc': 'TextEdit', 'Age55_69Pc': 'TextEdit', 'Age70upPct': 'TextEdit', 'HispanicPc': 'TextEdit', 'WhitePct': 'TextEdit', 'Black_Pct': 'TextEdit', 'Asian_Pct': 'TextEdit', 'Am_Indian': 'TextEdit', 'Pac_Island': 'TextEdit', 'Other_Race': 'TextEdit', 'Multi_Race': 'TextEdit', 'No_HS': 'Range', 'HS_Grad': 'Range', 'Some_Colle': 'Range', 'College': 'Range', 'unemprt_cy': 'TextEdit', });
lyr_PNA_Demographics_for_Dashboard_1.set('fieldLabels', {'STUD_AR_ID': 'no label', 'STUD_AR_NM': 'no label', 'STUD_AR_LB': 'no label', 'TOOLKIT_ID': 'no label', 'Acres': 'no label', 'AC_PER_1K': 'no label', 'RepPrkAc': 'no label', 'NEED_DESCP': 'no label', 'PCT_Walk': 'no label', 'aggregatio': 'no label', 'HasData': 'no label', 'ORIGINAL_O': 'no label', 'sourceCoun': 'no label', 'population': 'no label', 'householdt': 'no label', 'householdi': 'no label', 'educationa': 'no label', 'educatio_1': 'no label', 'educatio_2': 'no label', 'educatio_3': 'no label', 'educatio_4': 'no label', 'educatio_5': 'no label', 'educatio_6': 'no label', 'educatio_7': 'no label', 'educatio_8': 'no label', 'sports_mp3': 'no label', 'sports_m_1': 'no label', 'sports_m_2': 'no label', 'sports_m_3': 'no label', 'sports_m_4': 'no label', 'sports_m_5': 'no label', 'sports_m_6': 'no label', 'sports_m_7': 'no label', 'sports_m_8': 'no label', 'sports_m_9': 'no label', 'sports__10': 'no label', 'sports__11': 'no label', 'sports__12': 'no label', 'sports__13': 'no label', 'F5yearincr': 'no label', 'F5yearin_1': 'no label', 'F5yearin_2': 'no label', 'F5yearin_3': 'no label', 'F5yearin_4': 'no label', 'F5yearin_5': 'no label', 'F5yearin_6': 'no label', 'F5yearin_7': 'no label', 'F5yearin_8': 'no label', 'F5yearin_9': 'no label', 'F5yeari_10': 'no label', 'F5yeari_11': 'no label', 'F5yeari_12': 'no label', 'F5yeari_13': 'no label', 'F5yeari_14': 'no label', 'F5yeari_15': 'no label', 'F5yeari_16': 'no label', 'F5yeari_17': 'no label', 'F5yeari_18': 'no label', 'F1yearincr': 'no label', 'F1yearin_1': 'no label', 'MEAN_Asthm': 'no label', 'MEAN_Low_B': 'no label', 'MEAN_Cardi': 'no label', 'aggregat_1': 'no label', 'HasData_1': 'no label', 'ORIGINAL_1': 'no label', 'sourceCo_1': 'no label', 'raceandhis': 'no label', 'raceandh_1': 'no label', 'raceandh_2': 'no label', 'raceandh_3': 'no label', 'raceandh_4': 'no label', 'raceandh_5': 'no label', 'raceandh_6': 'no label', 'raceandh_7': 'no label', 'raceandh_8': 'no label', 'Age0_17Pct': 'no label', 'Age18_34Pc': 'no label', 'Age35_54Pc': 'no label', 'Age55_69Pc': 'no label', 'Age70upPct': 'no label', 'HispanicPc': 'no label', 'WhitePct': 'no label', 'Black_Pct': 'no label', 'Asian_Pct': 'no label', 'Am_Indian': 'no label', 'Pac_Island': 'no label', 'Other_Race': 'no label', 'Multi_Race': 'no label', 'No_HS': 'no label', 'HS_Grad': 'no label', 'Some_Colle': 'no label', 'College': 'no label', 'unemprt_cy': 'no label', });
lyr_PNA_Demographics_for_Dashboard_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});